
CREATE TABLE player(
id VARCHAR NOT NULL,
name VARCHAR NOT NULL,
email VARCHAR NOT NULL UNIQUE,
phone VARCHAR NOT NULL UNIQUE,
codename VARCHAR NOT NULL UNIQUE,
player_group INT NOT NULL,
PRIMARY KEY(id) 
);