
CREATE TABLE IF EXISTS player_tb (
id VARCHAR(255) NOT NULL,
player_name VARCHAR(50) NOT NULL UNIQUE,
email VARCHAR(100) NOT NULL UNIQUE,
phone VARCHAR(30) NOT NULL UNIQUE,
code_name VARCHAR(100) NOT NULL UNIQUE,
player_group ENUM('AVENGER','JUSTICE_LEAGUE') NOT NULL,
PRIMARY KEY (id)
);